// Mục lục kho học liệu – sinh tự động bởi .claude/skills/soan-khbd-toan/scripts/hoc_lieu_index.py. Không sửa tay.
window.HOC_LIEU = [
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 1. Sức hấp dẫn của truyện kể",
"file": "KHBD_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.docx",
"url": "mon/ngu_van/khbd/lop10/KHBD_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.docx",
"kb": 1143,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 2. Vẻ đẹp của thơ ca",
"file": "KHBD_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.docx",
"url": "mon/ngu_van/khbd/lop10/KHBD_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.docx",
"kb": 1126,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 3. Nghệ thuật thuyết phục trong văn nghị luận",
"file": "KHBD_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.docx",
"url": "mon/ngu_van/khbd/lop10/KHBD_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.docx",
"kb": 1143,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – Bài 1. Sức hấp dẫn của truyện kể",
"file": "SoDoTuDuy_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.png",
"url": "mon/ngu_van/khbd/lop10/SoDoTuDuy_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.png",
"kb": 143,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – Bài 2. Vẻ đẹp của thơ ca",
"file": "SoDoTuDuy_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.png",
"url": "mon/ngu_van/khbd/lop10/SoDoTuDuy_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.png",
"kb": 142,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – Bài 3. Nghệ thuật thuyết phục trong văn nghị luận",
"file": "SoDoTuDuy_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.png",
"url": "mon/ngu_van/khbd/lop10/SoDoTuDuy_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.png",
"kb": 156,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 1. Câu chuyện và điểm nhìn trong truyện kể",
"file": "KHBD_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.docx",
"url": "mon/ngu_van/khbd/lop11/KHBD_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.docx",
"kb": 1141,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 2. Cấu tứ và hình ảnh trong thơ trữ tình",
"file": "KHBD_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.docx",
"url": "mon/ngu_van/khbd/lop11/KHBD_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.docx",
"kb": 1129,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 3. Cấu trúc của văn bản nghị luận",
"file": "KHBD_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.docx",
"url": "mon/ngu_van/khbd/lop11/KHBD_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.docx",
"kb": 1131,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – Bài 1. Câu chuyện và điểm nhìn trong truyện kể",
"file": "SoDoTuDuy_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.png",
"url": "mon/ngu_van/khbd/lop11/SoDoTuDuy_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.png",
"kb": 151,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – Bài 2. Cấu tứ và hình ảnh trong thơ trữ tình",
"file": "SoDoTuDuy_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.png",
"url": "mon/ngu_van/khbd/lop11/SoDoTuDuy_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.png",
"kb": 145,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – Bài 3. Cấu trúc của văn bản nghị luận",
"file": "SoDoTuDuy_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.png",
"url": "mon/ngu_van/khbd/lop11/SoDoTuDuy_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.png",
"kb": 144,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 1. Khả năng lớn lao của tiểu thuyết",
"file": "KHBD_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.docx",
"url": "mon/ngu_van/khbd/lop12/KHBD_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.docx",
"kb": 1133,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 2. Những thế giới thơ",
"file": "KHBD_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.docx",
"url": "mon/ngu_van/khbd/lop12/KHBD_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.docx",
"kb": 1138,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 3. Lập luận trong văn bản nghị luận",
"file": "KHBD_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.docx",
"url": "mon/ngu_van/khbd/lop12/KHBD_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.docx",
"kb": 1135,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – Bài 1. Khả năng lớn lao của tiểu thuyết",
"file": "SoDoTuDuy_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.png",
"url": "mon/ngu_van/khbd/lop12/SoDoTuDuy_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.png",
"kb": 149,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – Bài 2. Những thế giới thơ",
"file": "SoDoTuDuy_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.png",
"url": "mon/ngu_van/khbd/lop12/SoDoTuDuy_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.png",
"kb": 154,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – Bài 3. Lập luận trong văn bản nghị luận",
"file": "SoDoTuDuy_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.png",
"url": "mon/ngu_van/khbd/lop12/SoDoTuDuy_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.png",
"kb": 148,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 10,
"ten": "Bài 1. Sức hấp dẫn của truyện kể",
"file": "Slide_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.pptx",
"url": "mon/ngu_van/slide/lop10/Slide_NGUVAN10_Bai1_SucHapDanCuaTruyenKe_T1-11.pptx",
"kb": 254,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 10,
"ten": "Bài 2. Vẻ đẹp của thơ ca",
"file": "Slide_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.pptx",
"url": "mon/ngu_van/slide/lop10/Slide_NGUVAN10_Bai2_VeDepCuaThoCa_T12-22.pptx",
"kb": 271,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 10,
"ten": "Bài 3. Nghệ thuật thuyết phục trong văn nghị luận",
"file": "Slide_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.pptx",
"url": "mon/ngu_van/slide/lop10/Slide_NGUVAN10_Bai3_NgheThuatThuyetPhucTrongVanNghiLuan_T23-35.pptx",
"kb": 285,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 11,
"ten": "Bài 1. Câu chuyện và điểm nhìn trong truyện kể",
"file": "Slide_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.pptx",
"url": "mon/ngu_van/slide/lop11/Slide_NGUVAN11_Bai1_CauChuyenVaDiemNhin_T1-11.pptx",
"kb": 293,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 11,
"ten": "Bài 2. Cấu tứ và hình ảnh trong thơ trữ tình",
"file": "Slide_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.pptx",
"url": "mon/ngu_van/slide/lop11/Slide_NGUVAN11_Bai2_CauTuVaHinhAnhTrongThoTruTinh_T12-22.pptx",
"kb": 256,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 11,
"ten": "Bài 3. Cấu trúc của văn bản nghị luận",
"file": "Slide_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.pptx",
"url": "mon/ngu_van/slide/lop11/Slide_NGUVAN11_Bai3_CauTrucCuaVanBanNghiLuan_T23-34.pptx",
"kb": 255,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 12,
"ten": "Bài 1. Khả năng lớn lao của tiểu thuyết",
"file": "Slide_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.pptx",
"url": "mon/ngu_van/slide/lop12/Slide_NGUVAN12_Bai1_KhaNangLonLaoCuaTieuThuyet_T1-11.pptx",
"kb": 277,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 12,
"ten": "Bài 2. Những thế giới thơ",
"file": "Slide_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.pptx",
"url": "mon/ngu_van/slide/lop12/Slide_NGUVAN12_Bai2_NhungTheGioiTho_T12-22.pptx",
"kb": 269,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "slide",
"khoi": 12,
"ten": "Bài 3. Lập luận trong văn bản nghị luận",
"file": "Slide_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.pptx",
"url": "mon/ngu_van/slide/lop12/Slide_NGUVAN12_Bai3_LapLuanTrongVanBanNghiLuan_T23-34.pptx",
"kb": 259,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 10,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 10",
"file": "MaTran_DacTa_NguVan10_HK1_2026-2027.docx",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan10_HK1_2026-2027.docx",
"kb": 39,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 10,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 10 (PDF)",
"file": "MaTran_DacTa_NguVan10_HK1_2026-2027.pdf",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan10_HK1_2026-2027.pdf",
"kb": 179,
"ngay": "2026-09-30"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 11,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 11",
"file": "MaTran_DacTa_NguVan11_HK1_2026-2027.docx",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan11_HK1_2026-2027.docx",
"kb": 39,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 11,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 11 (PDF)",
"file": "MaTran_DacTa_NguVan11_HK1_2026-2027.pdf",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan11_HK1_2026-2027.pdf",
"kb": 178,
"ngay": "2026-09-30"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 12,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 12",
"file": "MaTran_DacTa_NguVan12_HK1_2026-2027.docx",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan12_HK1_2026-2027.docx",
"kb": 39,
"ngay": "2026-10-01"
},
{
"mon": "ngu_van",
"tenMon": "Ngữ văn",
"loai": "ma_tran",
"khoi": 12,
"ten": "Ma trận và bản đặc tả đề kiểm tra định kỳ học kỳ I – Ngữ văn 12 (PDF)",
"file": "MaTran_DacTa_NguVan12_HK1_2026-2027.pdf",
"url": "mon/ngu_van/ma_tran/MaTran_DacTa_NguVan12_HK1_2026-2027.pdf",
"kb": 178,
"ngay": "2026-09-30"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "BÀI 1. GIỚI THIỆU KHÁI QUÁT MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.docx",
"url": "mon/sinh_hoc/khbd/lop10/KHBD_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.docx",
"kb": 1917,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "BÀI 2. PHƯƠNG PHÁP NGHIÊN CỨU VÀ HỌC TẬP MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.docx",
"url": "mon/sinh_hoc/khbd/lop10/KHBD_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.docx",
"kb": 1817,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "BÀI 3. CÁC CẤP ĐỘ TỔ CHỨC CỦA THẾ GIỚI SỐNG Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.docx",
"url": "mon/sinh_hoc/khbd/lop10/KHBD_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.docx",
"kb": 1913,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "BÀI 4. CÁC NGUYÊN TỐ HOÁ HỌC VÀ NƯỚC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.docx",
"url": "mon/sinh_hoc/khbd/lop10/KHBD_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.docx",
"kb": 1901,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – BÀI 1. GIỚI THIỆU KHÁI QUÁT MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.png",
"url": "mon/sinh_hoc/khbd/lop10/SoDoTuDuy_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.png",
"kb": 164,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – BÀI 2. PHƯƠNG PHÁP NGHIÊN CỨU VÀ HỌC TẬP MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.png",
"url": "mon/sinh_hoc/khbd/lop10/SoDoTuDuy_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.png",
"kb": 141,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – BÀI 3. CÁC CẤP ĐỘ TỔ CHỨC CỦA THẾ GIỚI SỐNG Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.png",
"url": "mon/sinh_hoc/khbd/lop10/SoDoTuDuy_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.png",
"kb": 163,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 10,
"ten": "Sơ đồ tư duy – BÀI 4. CÁC NGUYÊN TỐ HOÁ HỌC VÀ NƯỚC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.png",
"url": "mon/sinh_hoc/khbd/lop10/SoDoTuDuy_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.png",
"kb": 151,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "BÀI 1. KHÁI QUÁT VỀ TRAO ĐỔI CHẤT VÀ CHUYỂN HOÁ NĂNG LƯỢNG Sinh học 11 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "KHBD_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.docx",
"url": "mon/sinh_hoc/khbd/lop11/KHBD_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.docx",
"kb": 1904,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "BÀI 2. TRAO ĐỔI NƯỚC VÀ KHOÁNG Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 04 tiết",
"file": "KHBD_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.docx",
"url": "mon/sinh_hoc/khbd/lop11/KHBD_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.docx",
"kb": 1895,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "BÀI 4. QUANG HỢP Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 03 tiết",
"file": "KHBD_SINH11_Bai4_QuangHopOThucVat_T8-10.docx",
"url": "mon/sinh_hoc/khbd/lop11/KHBD_SINH11_Bai4_QuangHopOThucVat_T8-10.docx",
"kb": 1907,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 3. Thực hành: trao đổi nước và khoáng ở thực vật (bài học stem) sinh học 11 – kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.docx",
"url": "mon/sinh_hoc/khbd/lop11/KHBD_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.docx",
"kb": 1901,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – BÀI 1. KHÁI QUÁT VỀ TRAO ĐỔI CHẤT VÀ CHUYỂN HOÁ NĂNG LƯỢNG Sinh học 11 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "SoDoTuDuy_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.png",
"url": "mon/sinh_hoc/khbd/lop11/SoDoTuDuy_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.png",
"kb": 154,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – BÀI 2. TRAO ĐỔI NƯỚC VÀ KHOÁNG Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 04 tiết",
"file": "SoDoTuDuy_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.png",
"url": "mon/sinh_hoc/khbd/lop11/SoDoTuDuy_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.png",
"kb": 143,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – BÀI 4. QUANG HỢP Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 03 tiết",
"file": "SoDoTuDuy_SINH11_Bai4_QuangHopOThucVat_T8-10.png",
"url": "mon/sinh_hoc/khbd/lop11/SoDoTuDuy_SINH11_Bai4_QuangHopOThucVat_T8-10.png",
"kb": 157,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 11,
"ten": "Sơ đồ tư duy – Bài 3. Thực hành: trao đổi nước và khoáng ở thực vật (bài học stem) sinh học 11 – kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.png",
"url": "mon/sinh_hoc/khbd/lop11/SoDoTuDuy_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.png",
"kb": 149,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 2. Gene, hệ gene và quá trình truyền đạt thông tin di truyền sinh học 12 – kết nối tri thức với cuộc sống · 03 tiết",
"file": "KHBD_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.docx",
"url": "mon/sinh_hoc/khbd/lop12/KHBD_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.docx",
"kb": 1908,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "BÀI 3. ĐIỀU HOÀ BIỂU HIỆN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "KHBD_SINH12_Bai3_DieuHoaBieuHienGene_T5.docx",
"url": "mon/sinh_hoc/khbd/lop12/KHBD_SINH12_Bai3_DieuHoaBieuHienGene_T5.docx",
"kb": 1902,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "BÀI 4. ĐỘT BIẾN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "KHBD_SINH12_Bai4_DotBienGene_T6-7.docx",
"url": "mon/sinh_hoc/khbd/lop12/KHBD_SINH12_Bai4_DotBienGene_T6-7.docx",
"kb": 1888,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "BÀI 1. DNA VÀ CƠ CHẾ TÁI BẢN DNA (BÀI HỌC STEM) Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "KHBD_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.docx",
"url": "mon/sinh_hoc/khbd/lop12/KHBD_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.docx",
"kb": 1910,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – Bài 2. Gene, hệ gene và quá trình truyền đạt thông tin di truyền sinh học 12 – kết nối tri thức với cuộc sống · 03 tiết",
"file": "SoDoTuDuy_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.png",
"url": "mon/sinh_hoc/khbd/lop12/SoDoTuDuy_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.png",
"kb": 158,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – BÀI 3. ĐIỀU HOÀ BIỂU HIỆN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "SoDoTuDuy_SINH12_Bai3_DieuHoaBieuHienGene_T5.png",
"url": "mon/sinh_hoc/khbd/lop12/SoDoTuDuy_SINH12_Bai3_DieuHoaBieuHienGene_T5.png",
"kb": 154,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – BÀI 4. ĐỘT BIẾN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "SoDoTuDuy_SINH12_Bai4_DotBienGene_T6-7.png",
"url": "mon/sinh_hoc/khbd/lop12/SoDoTuDuy_SINH12_Bai4_DotBienGene_T6-7.png",
"kb": 140,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "khbd",
"khoi": 12,
"ten": "Sơ đồ tư duy – BÀI 1. DNA VÀ CƠ CHẾ TÁI BẢN DNA (BÀI HỌC STEM) Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "SoDoTuDuy_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.png",
"url": "mon/sinh_hoc/khbd/lop12/SoDoTuDuy_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.png",
"kb": 154,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 10,
"ten": "BÀI 1. GIỚI THIỆU KHÁI QUÁT MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.pptx",
"url": "mon/sinh_hoc/slide/lop10/Slide_SINH10_Bai1_GioiThieuKhaiQuatMonSinhHoc_T1-2.pptx",
"kb": 248,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 10,
"ten": "BÀI 2. PHƯƠNG PHÁP NGHIÊN CỨU VÀ HỌC TẬP MÔN SINH HỌC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.pptx",
"url": "mon/sinh_hoc/slide/lop10/Slide_SINH10_Bai2_PhuongPhapNghienCuuVaHocTapMonSinhHoc_T3-4.pptx",
"kb": 219,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 10,
"ten": "BÀI 3. CÁC CẤP ĐỘ TỔ CHỨC CỦA THẾ GIỚI SỐNG Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.pptx",
"url": "mon/sinh_hoc/slide/lop10/Slide_SINH10_Bai3_CacCapDoToChucCuaTheGioiSong_T5-6.pptx",
"kb": 238,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 10,
"ten": "BÀI 4. CÁC NGUYÊN TỐ HOÁ HỌC VÀ NƯỚC Sinh học 10 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.pptx",
"url": "mon/sinh_hoc/slide/lop10/Slide_SINH10_Bai4_CacNguyenToHoaHocVaNuoc_T7-8.pptx",
"kb": 229,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 11,
"ten": "BÀI 1. KHÁI QUÁT VỀ TRAO ĐỔI CHẤT VÀ CHUYỂN HOÁ NĂNG LƯỢNG Sinh học 11 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "Slide_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.pptx",
"url": "mon/sinh_hoc/slide/lop11/Slide_SINH11_Bai1_KhaiQuatTraoDoiChatChuyenHoaNangLuong_T1.pptx",
"kb": 221,
"ngay": "2026-10-01"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 11,
"ten": "BÀI 2. TRAO ĐỔI NƯỚC VÀ KHOÁNG Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 04 tiết",
"file": "Slide_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.pptx",
"url": "mon/sinh_hoc/slide/lop11/Slide_SINH11_Bai2_TraoDoiNuocVaKhoangOThucVat_T2-5.pptx",
"kb": 218,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 11,
"ten": "BÀI 4. QUANG HỢP Ở THỰC VẬT Sinh học 11 – Kết nối tri thức với cuộc sống · 03 tiết",
"file": "Slide_SINH11_Bai4_QuangHopOThucVat_T8-10.pptx",
"url": "mon/sinh_hoc/slide/lop11/Slide_SINH11_Bai4_QuangHopOThucVat_T8-10.pptx",
"kb": 236,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 11,
"ten": "Bài 3. Thực hành: trao đổi nước và khoáng ở thực vật (bài học stem) sinh học 11 – kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.pptx",
"url": "mon/sinh_hoc/slide/lop11/Slide_SINH11_STEM_Bai3_ThucHanhTraoDoiNuocVaKhoang_T6-7.pptx",
"kb": 221,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 12,
"ten": "Bài 2. Gene, hệ gene và quá trình truyền đạt thông tin di truyền sinh học 12 – kết nối tri thức với cuộc sống · 03 tiết",
"file": "Slide_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.pptx",
"url": "mon/sinh_hoc/slide/lop12/Slide_SINH12_Bai2_GeneHeGeneVaTruyenDatThongTinDiTruyen_T2-4.pptx",
"kb": 238,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 12,
"ten": "BÀI 3. ĐIỀU HOÀ BIỂU HIỆN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "Slide_SINH12_Bai3_DieuHoaBieuHienGene_T5.pptx",
"url": "mon/sinh_hoc/slide/lop12/Slide_SINH12_Bai3_DieuHoaBieuHienGene_T5.pptx",
"kb": 216,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 12,
"ten": "BÀI 4. ĐỘT BIẾN GENE Sinh học 12 – Kết nối tri thức với cuộc sống · 02 tiết",
"file": "Slide_SINH12_Bai4_DotBienGene_T6-7.pptx",
"url": "mon/sinh_hoc/slide/lop12/Slide_SINH12_Bai4_DotBienGene_T6-7.pptx",
"kb": 202,
"ngay": "2026-10-02"
},
{
"mon": "sinh_hoc",
"tenMon": "Sinh học",
"loai": "slide",
"khoi": 12,
"ten": "BÀI 1. DNA VÀ CƠ CHẾ TÁI BẢN DNA (BÀI HỌC STEM) Sinh học 12 – Kết nối tri thức với cuộc sống · 01 tiết",
"file": "Slide_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.pptx",
"url": "mon/sinh_hoc/slide/lop12/Slide_SINH12_STEM_Bai1_DNAVaCoCheTaiBanDNA_T1.pptx",
"kb": 219,
"ngay": "2026-10-01"
},
{
"mon": "tieng_anh",
"tenMon": "Tiếng Anh",
"loai": "ma_tran",
"khoi": 12,
"ten": "Ma trận và bản đặc tả đề ôn thi tốt nghiệp THPT – môn Tiếng Anh",
"file": "MaTran_DacTa_OnThiTN_TiengAnh_2026-2027.docx",
"url": "mon/tieng_anh/ma_tran/MaTran_DacTa_OnThiTN_TiengAnh_2026-2027.docx",
"kb": 39,
"ngay": "2026-10-01"
},
{
"mon": "tieng_anh",
"tenMon": "Tiếng Anh",
"loai": "ma_tran",
"khoi": 12,
"ten": "Ma trận và bản đặc tả đề ôn thi tốt nghiệp THPT – môn Tiếng Anh (PDF)",
"file": "MaTran_DacTa_OnThiTN_TiengAnh_2026-2027.pdf",
"url": "mon/tieng_anh/ma_tran/MaTran_DacTa_OnThiTN_TiengAnh_2026-2027.pdf",
"kb": 163,
"ngay": "2026-10-01"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 1. Mệnh đề (bản 4)",
"file": "KHBD_Bai1_MenhDe_Toan10_v4.docx",
"url": "mon/toan/khbd/lop10/KHBD_Bai1_MenhDe_Toan10_v4.docx",
"kb": 1360,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 2. Tập hợp và các phép toán (bản 4)",
"file": "KHBD_Bai2_TapHop_Toan10_v4.docx",
"url": "mon/toan/khbd/lop10/KHBD_Bai2_TapHop_Toan10_v4.docx",
"kb": 2399,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 3. Bất phương trình bậc nhất hai ẩn (bản 2)",
"file": "KHBD_Bai3_BPT_BacNhatHaiAn_Toan10_v2.docx",
"url": "mon/toan/khbd/lop10/KHBD_Bai3_BPT_BacNhatHaiAn_Toan10_v2.docx",
"kb": 1571,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài tập cuối chương I (PDF)",
"file": "KHBD_BaiTapCuoiChuong1_Toan10.pdf",
"url": "mon/toan/khbd/lop10/KHBD_BaiTapCuoiChuong1_Toan10.pdf",
"kb": 391,
"ngay": "2026-09-25"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài tập cuối chương I (bản 4)",
"file": "KHBD_BaiTapCuoiChuong1_Toan10_v4.docx",
"url": "mon/toan/khbd/lop10/KHBD_BaiTapCuoiChuong1_Toan10_v4.docx",
"kb": 1074,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Chuyên đề 1 – Hệ phương trình bậc nhất ba ẩn",
"file": "KHBD_CD1_Bai1_HePT_BacNhatBaAn_Toan10.docx",
"url": "mon/toan/khbd/lop10/KHBD_CD1_Bai1_HePT_BacNhatBaAn_Toan10.docx",
"kb": 809,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 4. Hệ bất phương trình bậc nhất hai ẩn",
"file": "KHBD_STEM_Bai4_HeBPT_KhauPhanAn_Toan10.docx",
"url": "mon/toan/khbd/lop10/KHBD_STEM_Bai4_HeBPT_KhauPhanAn_Toan10.docx",
"kb": 578,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 5. Giá trị lượng giác của một góc từ 0° đến 180°",
"file": "KHBD_TOAN10_Bai5_T16-17.docx",
"url": "mon/toan/khbd/lop10/KHBD_TOAN10_Bai5_T16-17.docx",
"kb": 1753,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài 6. Hệ thức lượng trong tam giác",
"file": "KHBD_TOAN10_Bai6_T18-21.docx",
"url": "mon/toan/khbd/lop10/KHBD_TOAN10_Bai6_T18-21.docx",
"kb": 1657,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 10,
"ten": "Bài tập cuối chương II",
"file": "KHBD_TOAN10_BaiTapCuoiChuong2_T15.docx",
"url": "mon/toan/khbd/lop10/KHBD_TOAN10_BaiTapCuoiChuong2_T15.docx",
"kb": 1064,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 1. Giá trị lượng giác của góc lượng giác (bản 3)",
"file": "KHBD_Bai1_GTLG_GocLuongGiac_Toan11_v3.docx",
"url": "mon/toan/khbd/lop11/KHBD_Bai1_GTLG_GocLuongGiac_Toan11_v3.docx",
"kb": 1568,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 2. Công thức lượng giác (bản 2)",
"file": "KHBD_Bai2_CongThucLuongGiac_Toan11_v2.docx",
"url": "mon/toan/khbd/lop11/KHBD_Bai2_CongThucLuongGiac_Toan11_v2.docx",
"kb": 590,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 3. Hàm số lượng giác (bản 2)",
"file": "KHBD_Bai3_HamSoLuongGiac_Toan11_v2.docx",
"url": "mon/toan/khbd/lop11/KHBD_Bai3_HamSoLuongGiac_Toan11_v2.docx",
"kb": 904,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 4. Phương trình lượng giác cơ bản",
"file": "KHBD_Bai4_PTLG_CoBan_Toan11.docx",
"url": "mon/toan/khbd/lop11/KHBD_Bai4_PTLG_CoBan_Toan11.docx",
"kb": 1601,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép biến hình",
"file": "KHBD_CD1_Bai1_PhepBienHinh_Toan11.docx",
"url": "mon/toan/khbd/lop11/KHBD_CD1_Bai1_PhepBienHinh_Toan11.docx",
"kb": 1088,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép tịnh tiến",
"file": "KHBD_CD1_Bai2_PhepTinhTien_Toan11.docx",
"url": "mon/toan/khbd/lop11/KHBD_CD1_Bai2_PhepTinhTien_Toan11.docx",
"kb": 1263,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép đối xứng trục",
"file": "KHBD_CD1_Bai3_PhepDoiXungTruc_Toan11.docx",
"url": "mon/toan/khbd/lop11/KHBD_CD1_Bai3_PhepDoiXungTruc_Toan11.docx",
"kb": 1238,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép quay và phép đối xứng tâm",
"file": "KHBD_CD1_Bai4_PhepQuay_DoiXungTam_Toan11.docx",
"url": "mon/toan/khbd/lop11/KHBD_CD1_Bai4_PhepQuay_DoiXungTam_Toan11.docx",
"kb": 1232,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 5. Dãy số",
"file": "KHBD_TOAN11_Bai5_T11-12.docx",
"url": "mon/toan/khbd/lop11/KHBD_TOAN11_Bai5_T11-12.docx",
"kb": 413,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 6. Cấp số cộng",
"file": "KHBD_TOAN11_Bai6_T13-14.docx",
"url": "mon/toan/khbd/lop11/KHBD_TOAN11_Bai6_T13-14.docx",
"kb": 598,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài 7. Cấp số nhân",
"file": "KHBD_TOAN11_Bai7_T15-16.docx",
"url": "mon/toan/khbd/lop11/KHBD_TOAN11_Bai7_T15-16.docx",
"kb": 410,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 11,
"ten": "Bài tập cuối chương I",
"file": "KHBD_TOAN11_BaiTapCuoiChuong1_T10.docx",
"url": "mon/toan/khbd/lop11/KHBD_TOAN11_BaiTapCuoiChuong1_T10.docx",
"kb": 538,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 1. Tính đơn điệu và cực trị của hàm số (bản 3)",
"file": "KHBD_Bai1_Toan12_DonDieu_CucTri_v3.docx",
"url": "mon/toan/khbd/lop12/KHBD_Bai1_Toan12_DonDieu_CucTri_v3.docx",
"kb": 2740,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 2. GTLN và GTNN của hàm số (bản 4)",
"file": "KHBD_Bai2_GTLN_GTNN_Toan12_v4.docx",
"url": "mon/toan/khbd/lop12/KHBD_Bai2_GTLN_GTNN_Toan12_v4.docx",
"kb": 764,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 3. Đường tiệm cận của đồ thị hàm số (bản 4)",
"file": "KHBD_Bai3_DuongTiemCan_Toan12_v4.docx",
"url": "mon/toan/khbd/lop12/KHBD_Bai3_DuongTiemCan_Toan12_v4.docx",
"kb": 940,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 12,
"ten": "Bài 4. Khảo sát và vẽ đồ thị hàm số (bản 3)",
"file": "KHBD_Bai4_Toan12_KhaoSatHamSo_v3.docx",
"url": "mon/toan/khbd/lop12/KHBD_Bai4_Toan12_KhaoSatHamSo_v3.docx",
"kb": 1864,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "khbd",
"khoi": 12,
"ten": "Chuyên đề 1 – Biến ngẫu nhiên rời rạc và các số đặc trưng",
"file": "KHBD_CD1_Bai1_Toan12_BienNgauNhienRoiRac.docx",
"url": "mon/toan/khbd/lop12/KHBD_CD1_Bai1_Toan12_BienNgauNhienRoiRac.docx",
"kb": 1207,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 1. Mệnh đề",
"file": "Slide_TOAN10_Bai1_T1-4.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_Bai1_T1-4.pptx",
"kb": 1109,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 2. Tập hợp và các phép toán",
"file": "Slide_TOAN10_Bai2_T5-8.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_Bai2_T5-8.pptx",
"kb": 2036,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 3. Bất phương trình bậc nhất hai ẩn",
"file": "Slide_TOAN10_Bai3_T10-11.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_Bai3_T10-11.pptx",
"kb": 1159,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 5. Giá trị lượng giác của một góc từ 0° đến 180°",
"file": "Slide_TOAN10_Bai5_T16-17.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_Bai5_T16-17.pptx",
"kb": 1603,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 6. Hệ thức lượng trong tam giác",
"file": "Slide_TOAN10_Bai6_T18-21.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_Bai6_T18-21.pptx",
"kb": 1312,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài tập cuối chương I",
"file": "Slide_TOAN10_BaiTapCuoiChuong1_T9.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_BaiTapCuoiChuong1_T9.pptx",
"kb": 833,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài tập cuối chương II",
"file": "Slide_TOAN10_BaiTapCuoiChuong2_T15.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_BaiTapCuoiChuong2_T15.pptx",
"kb": 667,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Chuyên đề 1 – Hệ phương trình bậc nhất ba ẩn",
"file": "Slide_TOAN10_CD1_Bai1_T1-5.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_CD1_Bai1_T1-5.pptx",
"kb": 495,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 10,
"ten": "Bài 4. Hệ bất phương trình bậc nhất hai ẩn",
"file": "Slide_TOAN10_STEM_Bai4_T12-14.pptx",
"url": "mon/toan/slide/lop10/Slide_TOAN10_STEM_Bai4_T12-14.pptx",
"kb": 226,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 1. Giá trị lượng giác của góc lượng giác",
"file": "Slide_TOAN11_Bai1_T1-3.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai1_T1-3.pptx",
"kb": 820,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 2. Công thức lượng giác",
"file": "Slide_TOAN11_Bai2_T4-5.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai2_T4-5.pptx",
"kb": 441,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 3. Hàm số lượng giác",
"file": "Slide_TOAN11_Bai3_T6-7.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai3_T6-7.pptx",
"kb": 752,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 4. Phương trình lượng giác cơ bản",
"file": "Slide_TOAN11_Bai4_T8-9.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai4_T8-9.pptx",
"kb": 789,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 5. Dãy số",
"file": "Slide_TOAN11_Bai5_T11-12.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai5_T11-12.pptx",
"kb": 454,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 6. Cấp số cộng",
"file": "Slide_TOAN11_Bai6_T13-14.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai6_T13-14.pptx",
"kb": 601,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài 7. Cấp số nhân",
"file": "Slide_TOAN11_Bai7_T15-16.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_Bai7_T15-16.pptx",
"kb": 421,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Bài tập cuối chương I",
"file": "Slide_TOAN11_BaiTapCuoiChuong1_T10.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_BaiTapCuoiChuong1_T10.pptx",
"kb": 408,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép biến hình",
"file": "Slide_TOAN11_CD1_Bai1_T1-2.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_CD1_Bai1_T1-2.pptx",
"kb": 894,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép tịnh tiến",
"file": "Slide_TOAN11_CD1_Bai2_T3-4.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_CD1_Bai2_T3-4.pptx",
"kb": 785,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép đối xứng trục",
"file": "Slide_TOAN11_CD1_Bai3_T5-6.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_CD1_Bai3_T5-6.pptx",
"kb": 590,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 11,
"ten": "Chuyên đề 1 – Phép quay và phép đối xứng tâm",
"file": "Slide_TOAN11_CD1_Bai4_T7-8.pptx",
"url": "mon/toan/slide/lop11/Slide_TOAN11_CD1_Bai4_T7-8.pptx",
"kb": 589,
"ngay": "2026-09-27"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 12,
"ten": "Bài 1. Tính đơn điệu và cực trị của hàm số",
"file": "Slide_TOAN12_Bai1_T1-6.pptx",
"url": "mon/toan/slide/lop12/Slide_TOAN12_Bai1_T1-6.pptx",
"kb": 956,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 12,
"ten": "Bài 2. GTLN và GTNN của hàm số",
"file": "Slide_TOAN12_Bai2_T7-9.pptx",
"url": "mon/toan/slide/lop12/Slide_TOAN12_Bai2_T7-9.pptx",
"kb": 418,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 12,
"ten": "Bài 3. Đường tiệm cận của đồ thị hàm số",
"file": "Slide_TOAN12_Bai3_T10-13.pptx",
"url": "mon/toan/slide/lop12/Slide_TOAN12_Bai3_T10-13.pptx",
"kb": 599,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 12,
"ten": "Bài 4. Khảo sát và vẽ đồ thị hàm số",
"file": "Slide_TOAN12_Bai4_T14-18.pptx",
"url": "mon/toan/slide/lop12/Slide_TOAN12_Bai4_T14-18.pptx",
"kb": 1040,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "slide",
"khoi": 12,
"ten": "Chuyên đề 1 – Biến ngẫu nhiên rời rạc và các số đặc trưng",
"file": "Slide_TOAN12_CD1_Bai1_T1-5.pptx",
"url": "mon/toan/slide/lop12/Slide_TOAN12_CD1_Bai1_T1-5.pptx",
"kb": 708,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "ma_tran",
"khoi": 10,
"ten": "Ma trận và bảng đặc tả đề luyện tập, ôn tập, kiểm tra định kỳ",
"file": "MaTran_DacTa_LuyenTap_Toan10_2026-2027.docx",
"url": "mon/toan/ma_tran/MaTran_DacTa_LuyenTap_Toan10_2026-2027.docx",
"kb": 61,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "ma_tran",
"khoi": 11,
"ten": "Ma trận và bảng đặc tả đề luyện tập, ôn tập, kiểm tra định kỳ",
"file": "MaTran_DacTa_LuyenTap_Toan11_2026-2027.docx",
"url": "mon/toan/ma_tran/MaTran_DacTa_LuyenTap_Toan11_2026-2027.docx",
"kb": 62,
"ngay": "2026-09-30"
},
{
"mon": "toan",
"tenMon": "Toán",
"loai": "ma_tran",
"khoi": 12,
"ten": "Ma trận và bảng đặc tả đề luyện tập, ôn tập, kiểm tra định kỳ",
"file": "MaTran_DacTa_LuyenTap_Toan12_2026-2027.docx",
"url": "mon/toan/ma_tran/MaTran_DacTa_LuyenTap_Toan12_2026-2027.docx",
"kb": 55,
"ngay": "2026-09-30"
}
,
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 1. Cấu trúc chất. Sự chuyển thể","file":"KHBD_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.docx","kb":5175,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 2. Nội năng. Định luật I nhiệt động lực học","file":"KHBD_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.docx","kb":5157,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 3. Nhiệt độ. Thang đo nhiệt độ","file":"KHBD_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.docx","kb":5168,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 4. Nhiệt dung riêng. Phương trình nhiệt lượng","file":"KHBD_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.docx","kb":5153,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 5. Nhiệt nóng chảy riêng","file":"KHBD_VATLY12_Bai5_NhietNongChayRieng_T9-10.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai5_NhietNongChayRieng_T9-10.docx","kb":5157,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Bài 6. Nhiệt hóa hơi riêng","file":"KHBD_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.docx","url":"mon/vat_li/khbd/lop12/KHBD_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.docx","kb":5150,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 1. Cấu trúc chất. Sự chuyển thể","file":"SoDoTuDuy_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.png","kb":175,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 2. Nội năng. Định luật I nhiệt động lực học","file":"SoDoTuDuy_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.png","kb":158,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 3. Nhiệt độ. Thang đo nhiệt độ","file":"SoDoTuDuy_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.png","kb":171,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 4. Nhiệt dung riêng. Phương trình nhiệt lượng","file":"SoDoTuDuy_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.png","kb":155,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 5. Nhiệt nóng chảy riêng","file":"SoDoTuDuy_VATLY12_Bai5_NhietNongChayRieng_T9-10.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai5_NhietNongChayRieng_T9-10.png","kb":159,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"khbd","khoi":12,"ten":"Sơ đồ tư duy – Bài 6. Nhiệt hóa hơi riêng","file":"SoDoTuDuy_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.png","url":"mon/vat_li/khbd/lop12/SoDoTuDuy_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.png","kb":152,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 1. Cấu trúc chất. Sự chuyển thể","file":"Slide_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai1_CauTrucChatSuChuyenThe_T1-2.pptx","kb":213,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 2. Nội năng. Định luật I nhiệt động lực học","file":"Slide_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai2_NoiNang_DinhLuatI_NDLH_T3-4.pptx","kb":198,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 3. Nhiệt độ. Thang đo nhiệt độ","file":"Slide_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai3_NhietDo_ThangDoNhietDo_T5-6.pptx","kb":210,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 4. Nhiệt dung riêng. Phương trình nhiệt lượng","file":"Slide_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai4_NhietDungRieng_PhuongTrinhNhietLuong_T7-8.pptx","kb":195,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 5. Nhiệt nóng chảy riêng","file":"Slide_VATLY12_Bai5_NhietNongChayRieng_T9-10.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai5_NhietNongChayRieng_T9-10.pptx","kb":197,"ngay":"2026-10-07"},
{"mon":"vat_li","tenMon":"Vật lí","loai":"slide","khoi":12,"ten":"Bài 6. Nhiệt hóa hơi riêng","file":"Slide_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.pptx","url":"mon/vat_li/slide/lop12/Slide_VATLY12_Bai6_NhietHoaHoiRieng_T11-12.pptx","kb":191,"ngay":"2026-10-07"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 1. Vị trí địa lí và phạm vi lãnh thổ Việt Nam","file":"KHBD_DIALY12_Bai1_ViTriDialiPhamViLanhTho_T1-2.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai1_ViTriDialiPhamViLanhTho_T1-2.docx","kb":40,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 2. Thiên nhiên nhiệt đới ẩm gió mùa","file":"KHBD_DIALY12_Bai2_ThienNhienNhietDoiAmGioMua_T3-6.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai2_ThienNhienNhietDoiAmGioMua_T3-6.docx","kb":40,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 3. Sự phân hoá đa dạng của thiên nhiên","file":"KHBD_DIALY12_Bai3_SuPhanHoaDaDangThienNhien_T7-10.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai3_SuPhanHoaDaDangThienNhien_T7-10.docx","kb":40,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 4. TH: Báo cáo về sự phân hoá thiên nhiên","file":"KHBD_DIALY12_Bai4_TH_BaoCaoSuPhanHoa_T11.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai4_TH_BaoCaoSuPhanHoa_T11.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 5. Vấn đề sử dụng hợp lí tài nguyên thiên nhiên và bảo vệ môi trường","file":"KHBD_DIALY12_Bai5_VanDeSDHopLiTNTNvaBVMT_T12.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai5_VanDeSDHopLiTNTNvaBVMT_T12.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 6. TH: Tuyên truyền bảo vệ môi trường","file":"KHBD_DIALY12_Bai6_TH_TuyenTruyenBVMT_T13.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai6_TH_TuyenTruyenBVMT_T13.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 7. Dân số Việt Nam","file":"KHBD_DIALY12_Bai7_DanSoVietNam_T14-15.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai7_DanSoVietNam_T14-15.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 8. Lao động và việc làm","file":"KHBD_DIALY12_Bai8_LaoDongVaViecLam_T16.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai8_LaoDongVaViecLam_T16.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Ôn tập giữa kì I","file":"KHBD_DIALY12_OnTapGiuaKi1_T17.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_OnTapGiuaKi1_T17.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 9. Đô thị hoá","file":"KHBD_DIALY12_Bai9_DoThiHoa_T19.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai9_DoThiHoa_T19.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 10. TH: Báo cáo dân cư","file":"KHBD_DIALY12_Bai10_TH_BaoCaoDanCu_T20.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai10_TH_BaoCaoDanCu_T20.docx","kb":38,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 11. Chuyển dịch cơ cấu kinh tế","file":"KHBD_DIALY12_Bai11_ChuyenDichCoCauKinhTe_T21.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai11_ChuyenDichCoCauKinhTe_T21.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 12. Vấn đề phát triển nông nghiệp","file":"KHBD_DIALY12_Bai12_VanDeNongNghiep_T22-24.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai12_VanDeNongNghiep_T22-24.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 13. Lâm nghiệp và thuỷ sản","file":"KHBD_DIALY12_Bai13_LamNghiepThuySan_T25-26.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai13_LamNghiepThuySan_T25-26.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 14. Tổ chức lãnh thổ nông nghiệp","file":"KHBD_DIALY12_Bai14_ToChucLanhThoNongNghiep_T27.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai14_ToChucLanhThoNongNghiep_T27.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 15. TH: Vẽ và cho biểu đồ nông nghiệp","file":"KHBD_DIALY12_Bai15_TH_VeChoBieuDo_T28.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai15_TH_VeChoBieuDo_T28.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 16. Chuyển dịch cơ cấu ngành công nghiệp","file":"KHBD_DIALY12_Bai16_ChuyenDichCoCauCongNghiep_T29.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai16_ChuyenDichCoCauCongNghiep_T29.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 17. Một số ngành công nghiệp","file":"KHBD_DIALY12_Bai17_MotSoNganhCongNghiep_T30-32.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai17_MotSoNganhCongNghiep_T30-32.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 18. Tổ chức lãnh thổ công nghiệp","file":"KHBD_DIALY12_Bai18_ToChucLanhThoCongNghiep_T33.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai18_ToChucLanhThoCongNghiep_T33.docx","kb":39,"ngay":"2026-10-08"},
{"mon":"dia_li","tenMon":"Địa lí","loai":"khbd","khoi":12,"ten":"Bài 19. TH: Vẽ biểu đồ và nhận xét công nghiệp","file":"KHBD_DIALY12_Bai19_TH_VeChoBieuDoCongNghiep_T34.docx","url":"mon/dia_li/khbd/lop12/KHBD_DIALY12_Bai19_TH_VeChoBieuDoCongNghiep_T34.docx","kb":39,"ngay":"2026-10-08"}
];
window.TEN_MON = {"toan": "Toán", "ngu_van": "Ngữ văn", "vat_li": "Vật lí", "hoa_hoc": "Hóa học", "sinh_hoc": "Sinh học", "lich_su": "Lịch sử", "dia_li": "Địa lí", "gdkt_pl": "GDKT&PL", "tieng_anh": "Tiếng Anh", "tin_hoc": "Tin học", "cong_nghe": "Công nghệ"};
